fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

valiknet_blog_posts:
    resource: "@ValiknetBlogBundle/Resources/config/routing.yml"
    type:     yaml
    prefix:   /